# How to configure the params of the program
# The program detects 

#### Length of seq that holds past keypoints coords
sequnece_length: 12
#### Horizontal swipe stride lengths
## Values between 5 - 10
right_arm_right_swipe_stride: 6.5
right_arm_left_swipe_stride: 7.5
left_arm_right_swipe_stride: 7.5
left_arm_left_swipe_stride: 6.5
#### vertical swipe stride lengths
## Values between 0.5 - 1.5
up_swipe_stride: 0.9
down_swipe_stride: 0.9
