#### Length of seq that holds past keypoints coords
sequnece_length: 4
#### Horizontal swipe stride lengths
## Values between 5 - 10
right_arm_right_swipe_stride: 7.5
right_arm_left_swipe_stride: 7.0
left_arm_right_swipe_stride: 7.0
left_arm_left_swipe_stride: 1.5
#### vertical swipe stride lengths
## Values between 0.5 - 1.5
up_swipe_stride: 0.6
down_swipe_stride: 0.6
